# Globalna biblioteka wulgaryzmĂłw PolskiBot
GLOBAL_BADWORDS = [
    "gĂłwno", "afa", "baÄ‡ siÄ™ o wĹ‚asnÄ… dupÄ™", "bajzel", "bladĹş", "bloĹ‚dĹĽob", "bĂłl dupy", "brandzlowaÄ‡ siÄ™", 
    "brandzlowanie", "buc", "burdelchata", "burdelĂłwa", "burdelĂłwka", "byle gĂłwno", "bzykaÄ‡", "bzykanko", 
    "ChWDP", "CJK", "certoliÄ‡ siÄ™", "chÄ™doĹĽenie", "cholera jasna", "cholernie", "chrzaniÄ‡ to", "chuj", 
    "chuj babski", "chuj bombki strzeliĹ‚", "chuj go wie", "chuj strzela", "chuj w dupÄ™", "chuj z tym", 
    "chujek", "chujnia", "chujnia z grzybniÄ…", "chujostwo", "chujowizna", "chujowo", "chujowoĹ›Ä‡", "chujowy", 
    "chujoza", "ciÄ…gnÄ…Ä‡ druta", "cichodajka", "ciemno jak w dupie", "cipa", "cipowanie", "cipowy", "ciuÄ‡ma", 
    "ciul", "ciulaÄ‡", "ciulnÄ…Ä‡", "coĹ› kogoĹ› pierdoli", "cwel", "cweliÄ‡", "cwelowanie", "cycatka", "cyckoman", 
    "daÄ‡ kopa w dupÄ™", "dawaÄ‡ dupy", "dmuchaÄ‡", "dmuchanie", "do cholery", "do chuja pana", "do dupy", 
    "do kurwy nÄ™dzy", "do rzici", "do usranego koĹ„ca", "do usranej Ĺ›mierci", "dobraÄ‡ siÄ™ do dupy", "dojebaÄ‡", 
    "dopierdalaÄ‡", "dopierdalanie", "dostaÄ‡ po dupie", "dostaÄ‡ wpierdol", "dupa", "dupa jasiu", "dupczenie", 
    "dupczyÄ‡", "dupiasty", "dupiaty", "dupnÄ…Ä‡", "dupny", "dupochron", "dupogodzina", "dupojebak", "dupojebstwo", 
    "dupoliz", "dymaÄ‡", "dymanko", "dziwka", "fiut", "frajer", "francuz", "gĹ‚Ä™bokie gardĹ‚o", "gnĂłj", "goĹ„ siÄ™", 
    "gĂłwniak", "gĂłwnianie", "gĂłwnianoĹ›Ä‡", "gĂłwniany", "gĂłwniara", "gĂłwniarz", "gĂłwnix", "gĂłwno prawda", 
    "gruby jak Ĺ›winia", "idĹş w chuj", "iĹ›Ä‡ na kurwy", "JP", "ja ciÄ™ pierdolÄ™", "ja pierdolÄ™", "jak skurwysyn", 
    "japa", "jasna cholera", "jebacz", "jebaÄ‡", "jebaÄ‡ to", "jebadeĹ‚kowo", "jebadĹ‚o", "jebak", "jebaka", "jebalnia", 
    "jebanie", "jebaniec", "jebankowo", "jebany", "jebaĹ„stwo", "jebliwoĹ›Ä‡", "jebnÄ…Ä‡", "jebniÄ™ty", "jebodrom", 
    "jebowaÄ‡", "jebu-jebu", "jprdl", "kakaÄ‡", "kakao", "kapa", "ki chuj", "kozak w necie, pizda w Ĺ›wiecie", 
    "kozojebca", "kurestwo", "kurewka", "kurewski", "kurewsko", "kurwa", "kurwa maÄ‡", "kurwa twoja maÄ‡", "kurwica", 
    "kurwiÄ‡", "kurwidoĹ‚ek", "kurwisko", "kurwiszcze", "kurwiszon", "kurwowaÄ‡", "kurwowanie", "kutafon", "kutas", 
    "kutasek", "kuĹşwica", "kuĹşwiÄ‡", "kuĹşwowaÄ‡", "lachociÄ…g", "laÄ‡ na to", "lataÄ‡ koĹ‚o chuja", "lizaÄ‡", "lodziara", 
    "MILF", "marcha", "matkojebca", "mela", "melaÄ‡", "menda", "mÄ™ska kurwa", "mieÄ‡ dupÄ™ na boku", "mieÄ‡ nasrane w gĹ‚owie", 
    "mieÄ‡ przejebane", "mieÄ‡ przesrane", "mieÄ‡ w dupie", "mieÄ‡ wyjebane", "na chuj", "na odpieprz", "na odpierdol", 
    "na odpierdziel", "na peĹ‚nej kurwie", "najebaÄ‡", "najebany", "napierdalaÄ‡", "napierdalanka", "napierdoliÄ‡", 
    "ni chuja", "nie ma chuja", "nie pierdoliÄ‡ siÄ™ w taĹ„cu", "nie urywaÄ‡ dupy", "niech to szlag", "niedojeb", 
    "niedopierdalanie", "niewydymka", "obciÄ…gacz", "obciÄ…ganie", "obciÄ…gnÄ…Ä‡", "oberwaÄ‡ po dupie", "obesraÄ‡", 
    "obiÄ‡ mordÄ™", "obrabiaÄ‡ dupÄ™", "obsraÄ‡", "obsraÄ‡ zbrojÄ™", "obsrywaÄ‡", "ochujeÄ‡", "ociulaÄ‡", "oczojebny", 
    "od cholery", "od chuja", "od dupy strony", "odjebaÄ‡", "odlewaÄ‡", "odpieprzaÄ‡", "odpieprzyÄ‡", "odpierdalaÄ‡", 
    "odpierdol", "odpierdoliÄ‡", "ogĂłr", "ojcojebca", "olaÄ‡ to", "opieprzaÄ‡", "opieprzyÄ‡", "opierdalaÄ‡", "osraÄ‡", 
    "oszczaÄ‡", "paĹ‚a", "parĂłwa", "pedaliÄ‡ siÄ™", "pedalskoĹ›Ä‡", "pedaĹ‚owaÄ‡", "pica", "piczka", "pieprz siÄ™", 
    "pieprznÄ…Ä‡", "pieprzyÄ‡", "pierdasiÄ‡", "pierdaszenie", "pierdniÄ™cie", "pierdol siÄ™", "pierdolec", "pierdolenie", 
    "pierdoliÄ‡", "pierdolnÄ…Ä‡", "pierdolniÄ™ty", "pierdolnik", "pierdolony", "pierdoĹ‚a", "pierdu-merdu", "pierdut", 
    "pierdyknÄ…Ä‡", "pierdziel", "pierdzieliÄ‡", "pies jebaĹ‚", "pijany w cztery dupy", "pinda", "pisdzielec", "pizda", 
    "pizdogrzeb", "pizdowaty", "pizgaÄ‡", "piĹşdziÄ‡", "piĹşdzielec", "po chuju", "po kiego chuja", "pocaĹ‚owaÄ‡ w dupÄ™", 
    "podjebaÄ‡", "podpierdalaÄ‡", "pojeb", "pojebaÄ‡", "pojebaniec", "pojebany", "pojebus", "pokurwowanie", "poĹ‚oĹĽyÄ‡ lachÄ™", 
    "popierdalaÄ‡", "popierdoleniec", "popierdoliĹ‚o", "popierdolony", "porucha", "posraniec", "posuwaÄ‡", "posuwadĹ‚o", 
    "posuwanie", "posuwanko", "pĂłjĹ›Ä‡ siÄ™ jebaÄ‡", "przechuj", "przecweliÄ‡", "przelecieÄ‡", "przepierdoliÄ‡", "przerĹĽnÄ…Ä‡", 
    "przydupas", "przyjebaÄ‡", "przypierdalaÄ‡", "przypierdzieliÄ‡", "robiÄ‡ koĹ‚o dupy", "robiÄ‡ laskÄ™", "robiÄ‡ loda", 
    "robiÄ‡ minetÄ™", "robiÄ‡ w chuja", "rozjebaÄ‡", "rozpierdol", "rozpierdolony", "rĂłw", "ruchable", "ruchacz", 
    "ruchaÄ‡", "ruchanko", "rura", "ruszyÄ‡ dupÄ™", "rympaĹ‚", "rzucaÄ‡ kurwami", "rzucaÄ‡ kuĹşwami", "rĹĽnÄ…Ä‡", "samojebka", 
    "siedzieÄ‡ na dupie", "siedzieÄ‡ po uszy w gĂłwnie", "siusiumajtek", "skofia", "skurwiaĹ‚y", "skurwiel", "skurwysyn", 
    "spierdalaÄ‡", "spierdoliÄ‡", "spizgany", "sprÄ™ĹĽynĂłwka", "spuszczaÄ‡", "sraczka", "sraczyk", "sraÄ‡", "srajtaĹ›ma", 
    "srak", "sraka", "stukaÄ‡", "sucz", "suczka", "suka", "sukinsyn", "szajs", "szajspapier", "szmata", "szon", "sztos", 
    "Ĺ›cierka", "Ĺ›wiÄ™tojebliwoĹ›Ä‡", "Ĺ›wiÄ™tojebliwy", "Ĺ›winia", "Ĺ›wiĹ„ski ryj", "towar", "truÄ‡ dupÄ™", "trzepaÄ‡ kapucyna", 
    "trzÄ™sidupa", "twoja stara", "udupiÄ‡", "ujebaÄ‡", "ujebany", "upierdliwiec", "upierdliwy", "upierdoliÄ‡", "upierdolony", 
    "w chuj", "w dupÄ™ jebany", "w dupie", "w pizdu", "walcowaÄ‡", "waliÄ‡", "waliÄ‡ konia", "waliÄ‡ w chuja", "waĹ‚", 
    "wkurwiaÄ‡", "wkurwianie", "wkurwienie", "wkurwiony", "wkuĹşwiaÄ‡", "wĂłr", "wpieprzyÄ‡", "wpierdalaÄ‡", "wpierdol", 
    "wpierdoliÄ‡", "wrzĂłd na dupie", "wsadziÄ‡ sobie w dupÄ™", "wychujaÄ‡", "wyjebaÄ‡", "wyjebany", "wyjebisty", "wyjebka", 
    "wykurwiĹ›cie", "wypierdalaÄ‡", "wypierdek", "wypidĹşiewo", "wyrywaÄ‡ dupy", "wysraÄ‡", "wziÄ…Ä‡ dupÄ™ w troki", 
    "z dupy", "za chuja", "zajebaÄ‡", "zajebisty", "zajebiĹ›cie", "zajebus", "zajob", "zakisiÄ‡ ogĂłra", "zakurwiĹ›cie", 
    "zapieprzaÄ‡", "zapieprzyÄ‡", "zapierdalaÄ‡", "zapierdalanie", "zapierdoliÄ‡", "zapiĹşdziaĹ‚y", "zasraniec", 
    "zasrany", "zawracaÄ‡ dupÄ™", "zdupny", "zdzira", "zesraÄ‡ siÄ™", "zjeb", "zjebaÄ‡", "zjebany", "zrobiÄ‡ w chuja"
]
